[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services/index.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery/index.html"
  status = 200